[package]
name = "rocksbin"
version = "0.1.0"
authors = ["Birk Tjelmeland <birktjelmeland@yahoo.no>"]
license = "MIT"

[dependencies]
rocksdb = "0.10"
serde = "1.0"
bincode = "1.0"

[dev-dependencies]
tempfile = "3.0"
serde_derive = "1.0"
